version: '3.9'
services:
  #zookeeper service to communicate ana manage kafka
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  broker:
    container_name: broker
    image: confluentinc/cp-kafka:7.5.0
    ports:
      #wxternal connections to broker outside docker use 9092 and host.docker.internal
      - "9092:9092"
      #internal connections(inside docker) and container host name broker
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092 , PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafka_ui:
    container_name: kafka_ui
    image: provectuslabs/kafka-ui
    ports:
      - "8015:8015"
    environment:
      KAFKA_CLUSTER_NAME: local
      KAFKA_CLUSTER_BOOTSTRAPSERVER: broker:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - broker
